spring.application.name=servicio-gateway
server.port=8080

# Clave secreta para validar el JWT.
# Debe ser igual a la del servicio-autenticacion.
jwt.secret=NexoCommerceSecretKeyParaJWTDebeTenerMinimo32Caracteres2026
# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Ruta hacia servicio-autenticacion
spring.cloud.gateway.server.webflux.routes[0].id=servicio-autenticacion
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# Ruta hacia servicio-usuarios
spring.cloud.gateway.server.webflux.routes[1].id=servicio-usuarios
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/usuarios/**

# Ruta hacia servicio-productos
spring.cloud.gateway.server.webflux.routes[2].id=servicio-productos
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/productos/**

# Ruta hacia servicio-pedidos
spring.cloud.gateway.server.webflux.routes[3].id=servicio-pedidos
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/pedidos/**

# Ruta hacia servicio-pagos
spring.cloud.gateway.server.webflux.routes[4].id=servicio-pagos
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/pagos/**

# Ruta hacia servicio-notificaciones
spring.cloud.gateway.server.webflux.routes[5].id=servicio-notificaciones
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/notificaciones/**

# Ruta hacia servicio-reportes
spring.cloud.gateway.server.webflux.routes[6].id=servicio-reportes
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/reportes/**